name: wlm
description: worship lyrics mara & mizo app.
publish_to: 'none' 
version: 1.1.2+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.12 
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  buttons_tabbar: ^1.3.8
  
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  image_path: "app_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:     
    - assets/lili.png


family: 'Raleway'
fonts:
  - asset: assets/fonts/Raleway-Regular.ttf
    weight: 400
  - asset: assets/fonts/Raleway-Bold.ttf
    weight: 700
    
