const maraSongTitles = [
  '1.  Above all                                                                                       (Hmotaotheina zy)',
  '2.  Aku thatlona chho lia                                                                           (Pachhatuhpa ta eina vaih thlâh haw)',
  '3.  Ato ei hla khai                                                                                 (Zisu hnohta ato ei hlâ)',
  '4.  Bei chaipa ta kei moleipa                                                                       (who say I am)',
  '5.  Beipa chaw pangai',
  '6.  Beipa na ngiathai mah y                                                                         (Krista kyhpachâna)',
  '7.  Beipa, na pachâ chi                                                                             (Nopona ei tyhpa hryta)',
  '8.  Beipa phana                                                                                     (Goodness of God)',
  '9.  Cha kraw cha ei patu lyma aw                                                                    (The old rugged cross)',
  '10. Chhâzaw ta rônahna ta y se                                                                      (Thlâpâ nah awhsi zy)',
  '11. Eima lika lia lei chiepa a y                                                                    (Living hope)',
  '12. Eina chhi tyh                                                                                   (Khazohpa ta einâ chhi tyh)',
  '13. Eina chhina maih ei sie aw                                                                      (Zisu ta chhôh nah zâ nâ chhi)',
  '14. EI THLAHPA NA PACHHA HAW                                                                        (My redeemer lives)',
  '15. Ei thyu aw na, ei paw o lȃ ',
  '16. Ei sah hlupi                                                                                    (10000 reason)',
  '17. El Dorado                                                                                       (Aw ei hro yru pa heta)',
  '18. He khizaw râh lia bao hela                                                                      (Maophyu khei ngâhpa ta beipa chakao su vy)',
  '19. Hmotaotheina zy                                                                                 (Cha khaipa ei)',
  '20. Hrona thikhao                                                                                   (Khizaw hela leidia khai ha hrasala)',
  '21. Hy Beipa ei cha ngia ngaita                                                                     (Lord I need you)',
  '22. Hy Bei Khazoh na hmotaopa zydua he                                                              (Ei thlahpa ta cha reithai khoh,Beipa)',
  '23. Hy Khazoh ! Nâ Beichhai na châ',
  '24. HY RÔHNAH CHAI                                                                                  (Noh nah thlapa, awhsi zy)',
  '25. Kei dei na siesai aw vei                                                                        (Chieleinazy rairunazy)',
  '26. Khizaw hmozy hmâ pata                                                                           (He khizaw hmo zydua hela rei a daih aw vei)',
  '27. Khizaw thaina nah sona zy                                                                       ( Ei molei phaohri chhao)',
  '28. Khizaw he lei hrasa ',
  '29. Khizaw chyhsa nata na mohmô lia                                                                 (Beipa ei chô lia ta na phana he)',
  '30. Khophie chhao pahno ma pi                                                                       (Noh tota bei zisu kyh ei pachâ via rili tyh)',
  '31. Kraws liata thisai soh a y                                                                      (Hy, thisai rohna chaipa)',
  '32. Kraws thaby lia                                                                                 (At the cross)',
  '33. Kraws va eima chaly ',
  '34. Krista â dai paki                                                                               (Christ is enough)',
  '35. Kyhpachâna! Noâh â chhih                                                                        (Kyhpachâna  reih thai sala)',
  '36. Moh la na hro aw                                                                                (Kalvary lia pachhatu moh la)',
  '37. Moh ngia chhaipa                                                                                (What a beautiful name)',
  '38. Na molei phaohri pahlei na khoh ma?                                                             (Hmotaitheina noâhpa a y)',
  '39. Nâ Ngiahthai mah y                                                                              (Krista kyhpachâna)',
  '40. Nazari Zisu ',
  '41. Olive thohna',
  '42. Pachhatuh ahro ',
  '43. Pachhatuh, kei na khôsai kha                                                                    (Zisu, Zisu, ei awhna thei la)',
  '44. Pakho teh u                                                                                     (Mopathaihpazy, moh teh u)',
  '45. Pathipalôh molei chiehpa ',
  '46. Paw Khazoh kypachâna',
  '47. SAKHIH DÂHPHIPA HAWH',
  '48. Still',
  '49. Shout to the Lord',
  '50. Thlahpa Pathaih ',
  '51. The blessing',
  '52. Ti, wine lâ na pachâsa',
  '53. Zisu ei viasa pha chai                                                                         (Hrochhôh ei zi lymâ aw)',
  '54. Zisu eima viasa pha chai',
  '55. Zisu hnei ei khoh via',
];

const mizoSongTitles = [
  '1.  A hmangaihna a lo ni',
  '2.  Aman engkimah min hria e'
];

const danceSongTitles = [
  '1. Ape',
  '2. Chacha la ei pasie',
  '3. Ei reithai lyma aw',
  '3. Hallelujah',
  '4. Na hro lia lyna na kho ma',
  '5. Na lia ato ei tao thei',
  '6. Tui nung lui chu',
];
