const maraSongTitles = [
  '1. Above all (Hmotaotheina zy)',
  '2. Aku thatlona chho lia (Pachhatuhpa ta eina vaih thlâh haw)',
  '3. Ato ei hla khai (Zisu hnohta ato ei hlâ)',
  '4. Bei chaipa ta kei moleipa (who say I am)',
];

const mizoSongTitles = [
  '1.  Ani chuan kan thiltih angte ni loin',
  '2.  El Dorado',
  '3.	Engtia awm thei nge?',
  '4.  Eng nge ka lungngaih ang',
  '5.	Hmangaih tu',
  '6.  He khawvel leh a ropuina te',
  '7.  Hringnun kan zin kawngah hian',
  '8.	I hlu ani',
  '9.	I lam kan lo hawi',
  '10.	Ka lawm e isu',
  '11.	Ka thupui ber',
  '12.	Ka lawm e Lalpa',
  '13.  Ka dai zel dawn',
  '14.  Ka tling si lo',
  '15.  Ka thlarau a chawm leh thin',
  '16.  Ka Lalpa min hruaina hi',
  '17.  Kum tam tak chhung hmangaihtu hre lo in',
  '18.  Lei hringnun khualzin kawngah hian',
  '19.	Min tiharh leh rawh',
  '20.	Min hmangaih loh I thei lo',
  '21.	Min chhungkhat la',
  '22.  Min hmangaih si a',
  '23.  Min hruai la ka zui ang che',
  '24.	Nang ka Himna I ni si',
  '25.	Nazareth',
  '26.  Nang fak zel che',
  '27.	Nitin hian',
  '28.  Nang nen chuan',
  '29.  Nawmsaknate zawngin ka tlan thin',
  '30.  Nitin in',
  '31.	Rimawi ropui ber',
  '32.  Sual Setanan rei tak min lo bum',
  '33.  Sualbumna lamtluang zawhin',
  '34.	Tlawm lua mah la',
  '35.	Thlei bîk a nei lo',
  '36.  Thian tha ber Isua',
  '37.  Ka thinglung a nung',
  '38.  Chawimawina zawng ka hlan a che',
  '39.  Aman engkimah min hria',
  '40.  Isua Lal ber ani',
  '41.  indona',
  '42.  Phulo hmangaihna',
  '43.  Duhthlana sang ber',
  '44.  Pathian Hmelduhawm',
  '45.  Ka nun hnarkaitu',
  '46.  Hei leh chen',
  '47.  ka damlai nun kawng',
  '48.  Ka duhsamber',
  '49.  Ka tawr hi Lalpan a phal',
  '50.  Ka rawn in hlan e',
];

const danceSongTitles = [
  '1. Ape',
  '2. Chacha la ei pasie',
  '3. Ei reithai lyma aw',
  '3. Hallelujah',
  '4. Na hro lia lyna na kho ma',
  '5. Na lia ato ei tao thei',
  '6. Tui nung lui chu',
];
