import 'package:wlm/song/song_lyric.dart';

const songInfo = [
  {
    'id': '0001',
    'title': 'A hmangaihna a lo ni',
    'language': 'mizo',
    'lyrics': ahmangaihnaaloni,
    'link': 'https://youtu.be/HjBo0q0EPtM'
  },
  {
    'id': '0002',
    'title': 'An hrilhfiah',
    'language': 'mizo',
    'lyrics': anhrilhfiah,
    'link': 'https://youtu.be/lMUZgcUYzDM',
  },
  {
    'id': '0003',
    'title': 'Aman engkimah min hria e',
    'language': 'mizo',
    'lyrics': amanengkimahminhria,
    'link': 'https://youtu.be/vkp590eaSz4',
  },
  {
    'id': '0004',
    'title': 'Amen ka pe lo thei lo',
    'language': 'mizo',
    'lyrics': amenkapelotheilo,
    'link': 'https://youtu.be/m8IEpdpME6Y',
  },
  {
    'id': '0005',
    'title': 'Amen! Silfai ka ni',
    'language': 'mizo',
    'lyrics': amenSilfaikani,
    'link': 'https://youtu.be/khlqJCfLKQI',
  },
  {
    'id': '0006',
    'title': 'A ṭha e',
    'language': 'mizo',
    'lyrics': athae,
    'link': 'https://youtu.be/jpGi1wVPyzI',
  },
  {
    'id': '0007',
    'title': 'Aw ropuiber',
    'language': 'mizo',
    'lyrics': awropuiber,
    'link': 'https://youtu.be/HbBqjiMVafk',
  },
  {
    'id': '0008',
    'title': 'Bultan min phal sak',
    'language': 'mizo',
    'lyrics': bultanminphalsak,
    'link': 'https://youtu.be/Csi67pEKH3A',
  },
  {
    'id': '0009',
    'title': 'Chawimawina',
    'language': 'mizo',
    'lyrics': chawmawinazawngkahlanche,
    'link': 'https://youtu.be/59tSCeBuxQY',
  },
  {
    'id': '0010',
    'title': 'Chhandamtu min hruaina lamtluang',
    'language': 'mizo',
    'lyrics': chhandamtuminhruainalamtluang,
    'link': 'https://youtu.be/TUoBoXChYfU',
  },
  {
    'id': '0011',
    'title': 'Danglamlo krista',
    'language': 'mizo',
    'lyrics': danglamlokrista,
    'link': 'https://youtu.be/Bkc7DlcPmpE',
  },
  {
    'id': '0012',
    'title': 'Duhthlanna sang ber',
    'language': 'mizo',
    'lyrics': duhthlannasangber,
    'link': 'https://youtu.be/-82eQDK-bbs',
  },
  {
    'id': '0013',
    'title': 'Engtia awm thei nge?',
    'language': 'mizo',
    'lyrics': engtiaawmtheinge,
    'link': 'https://youtu.be/G9aUVdBjSwY',
  },
  {
    'id': '0014',
    'title': 'Eng vang nge',
    'language': 'mizo',
    'lyrics': engvangnge,
    'link': 'https://youtu.be/QcvBD6B4RYM',
  },
  {
    'id': '0015',
    'title': 'El Dorado',
    'language': 'mizo',
    'lyrics': eldoradomizo,
    'link': 'https://youtu.be/8ukstCOI174',
  },
  {
    'id': '0016',
    'title': 'Hmangaihtu',
    'language': 'mizo',
    'lyrics': hmangaihtu,
    'link': 'https://youtu.be/3hqA7exUg0U',
  },
  {
    'id': '0017',
    'title': 'Hringnun kan zin kawngah hian',
    'language': 'mizo',
    'lyrics': hringnunkanzinkawngahhian,
    'link': 'https://youtu.be/OY5-hzSceEU',
  },
  {
    'id': '0018',
    'title': 'Hriatchian lehzual che hi',
    'language': 'mizo',
    'lyrics': hriatchianlehzualchehi,
    'link': 'https://youtu.be/frY-352fu1A',
  },
  {
    'id': '0019',
    'title': 'I hlu a ni',
    'language': 'mizo',
    'lyrics': hriatchianlehzualchehi,
    'link': 'https://youtu.be/y9wr46Pe6xI',
  },
  {
    'id': '0020',
    'title': 'I lam kan lo hawi',
    'language': 'mizo',
    'lyrics': ilamkanlohawi,
    'link': 'https://youtu.be/NglqcMbMdzY',
  },
  {
    'id': '0021',
    'title': 'Indona',
    'language': 'mizo',
    'lyrics': ilamkanlohawi,
    'link': 'https://youtu.be/kdNakn06vdI',
  },
  {
    'id': '0022',
    'title': 'Isua Lal ber ani',
    'language': 'mizo',
    'lyrics': isualalber,
    'link': 'https://youtu.be/NeD1ANr_IiI',
  },
  {
    'id': '0023',
    'title': 'I zalen',
    'language': 'mizo',
    'lyrics': izalen,
    'link': 'https://youtu.be/FLX4d02tdX0',
  },
  {
    'id': '0024',
    'title': 'Ka dam lai nun kawng',
    'language': 'mizo',
    'lyrics': kadamlainunkawng,
    'link': 'https://youtu.be/ToF0vmgtw8c',
  },
  {
    'id': '0025',
    'title': 'Ka dai zel dawn',
    'language': 'mizo',
    'lyrics': kadaizeldawn,
    'link': 'https://youtu.be/otKn2dgP9YI',
  },
  {
    'id': '0026',
    'title': 'Ka duh ber Lalpa',
    'language': 'mizo',
    'lyrics': kaduhberlalpa,
    'link': 'https://youtu.be/s-IKpi4B3UI',
  },
  {
    'id': '0027',
    'title': 'ka hnaih nan che',
    'language': 'mizo',
    'lyrics': kahnaihnanche,
    'link': 'https://youtu.be/IJqYPjI5WOM',
  },
  {
    'id': '0028',
    'title': 'Ka lawm e Isu',
    'language': 'mizo',
    'lyrics': kalawmeisu,
    'link': 'https://youtu.be/M6LozoEWfg8',
  },
  {
    'id': '0029',
    'title': 'Ka lawm e Lalpa',
    'language': 'mizo',
    'lyrics': kalawmelalpa,
    'link': 'https://youtu.be/1bKn5OCkkyE',
  },
  {
    'id': '0030',
    'title': 'ka lo kir e',
    'language': 'mizo',
    'lyrics': kalokire,
    'link': 'https://youtu.be/h1hQrMOIb5Y',
  },
  {
    'id': '0031',
    'title': 'Kan fak che',
    'language': 'mizo',
    'lyrics': kanfakche,
    'link': 'https://youtu.be/Ets6LriJm-w',
  },
  {
    'id': '0032',
    'title': 'Kan thinlung kan hlan che',
    'language': 'mizo',
    'lyrics': kanthinlunghi,
    'link': 'https://youtu.be/TT1kE6tDwU4',
  },
  {
    'id': '0033',
    'title': 'Ka nun hnâr kaitu',
    'language': 'mizo',
    'lyrics': kanunhnarkaitu,
    'link': 'https://youtu.be/p_OUNpEEx3w',
  },
  {
    'id': '0034',
    'title': 'Kan zai I tan',
    'language': 'mizo',
    'lyrics': kanzaiitan,
    'link': 'https://youtu.be/TxBERRbz-W0',
  },
  {
    'id': '0035',
    'title': 'Ka rawn in hlan e',
    'language': 'mizo',
    'lyrics': karawninhlane,
    'link': 'https://youtu.be/9eD07EG2FTw',
  },
  {
    'id': '0036',
    'title': 'Ka rinchhan Lalpa',
    'language': 'mizo',
    'lyrics': karinchhanLalpan,
    'link': 'https://youtu.be/Yq0sEFQu6hc',
  },
  {
    'id': '0037',
    'title': 'Ka ring zel ang che',
    'language': 'mizo',
    'lyrics': karingzelangche,
    'link': 'https://youtu.be/HGCvnnk_TjQ',
  },
  {
    'id': '0038',
    'title': 'Ka tawrh hi Lalpan a phal',
    'language': 'mizo',
    'lyrics': katawrhhilalpanaphal,
    'link': 'https://youtu.be/G4fr3PDVLy8',
  },
  {
    'id': '0039',
    'title': 'Ka tling si lo',
    'language': 'mizo',
    'lyrics': katlingsilo,
    'link': 'https://youtu.be/AS4JhjKzso0',
  },
  {
    'id': '0040',
    'title': 'Ka thinglungah a nung',
    'language': 'mizo',
    'lyrics': kathinglungahanung,
    'link': 'https://youtu.be/yDd9UNuhHv8',
  },
  {
    'id': '0041',
    'title': 'Ka thupui ber',
    'language': 'mizo',
    'lyrics': kathupuiber,
    'link': 'https://youtu.be/wsnJvCxgAX8',
  },
  {
    'id': '0042',
    'title': 'Ka zawng zawng hian fak che a nuam',
    'language': 'mizo',
    'lyrics': kazawngzawnghianfakcheanuam,
    'link': 'https://youtu.be/axt9darYYbk',
  },
  {
    'id': '0043',
    'title': 'Khawngaihna',
    'language': 'mizo',
    'lyrics': khawngaihna,
    'link': 'https://youtu.be/lgEC3Z8XhDY',
  },
  {
    'id': '0044',
    'title': 'Kraws kawng',
    'language': 'mizo',
    'lyrics': krawkawng,
    'link': 'https://youtu.be/k2M2S9WSnBQ',
  },
  {
    'id': '0045',
    'title': 'Lalpa atha ani',
    'language': 'mizo',
    'lyrics': lalpaathaani,
    'link': 'https://youtu.be/oPvMhkiQ1m0',
  },
  {
    'id': '0046',
    'title': 'Lalpa atha',
    'language': 'mizo',
    'lyrics': lalpaatha,
    'link': 'https://youtu.be/en82XRTJJW8',
  },
  {
    'id': '0047',
    'title': 'Lalpa thatna',
    'language': 'mizo',
    'lyrics': lalpathatna,
    'link': 'https://youtu.be/W-bGOi9Cmls',
  },
  {
    'id': '0048',
    'title': 'Lalpa Ini',
    'language': 'mizo',
    'lyrics': lalpaini,
    'link': 'https://youtu.be/N1ttXyN3Iag',
  },
  {
    'id': '0049',
    'title': 'Lalpa mi hriat',
    'language': 'mizo',
    'lyrics': lalpamihriat,
    'link': 'https://youtu.be/-4v9EyBODKM',
  },
  {
    'id': '0050',
    'title': 'Lalpan min hria',
    'language': 'mizo',
    'lyrics': lalpaminhria,
    'link': 'https://youtu.be/26SHA1vh1fI',
  },
  {
    'id': '0051',
    'title': 'Lalpa remruat',
    'language': 'mizo',
    'lyrics': lalparemruat,
    'link': 'https://youtu.be/xHjsd0ibTAM',
  },
  {
    'id': '0052',
    'title': 'Min chhung khat la',
    'language': 'mizo',
    'lyrics': minchhungkhatla,
    'link': 'https://youtu.be/x5xIfH2ELYk',
  },
  {
    'id': '0053',
    'title': 'Min dilsak thin',
    'language': 'mizo',
    'lyrics': mindilsakthin,
    'link': 'https://youtu.be/iMbMxNn3bqg',
  },
  {
    'id': '0054',
    'title': 'Min hmangaih loh i thei lo',
    'language': 'mizo',
    'lyrics': minhmangaihlohItheilo,
    'link': 'https://youtu.be/uoUeGX3gcNQ',
  },
  {
    'id': '0055',
    'title': 'Min hmangaih si a',
    'language': 'mizo',
    'lyrics': minhmangaihsia,
    'link': 'https://youtu.be/5i7bVytO1As',
  },
  {
    'id': '0056',
    'title': 'Min hruai la ka zui ang che',
    'language': 'mizo',
    'lyrics': minhruailakazuiangche,
    'link': 'https://youtu.be/tNqw2gtIuaY',
  },
  {
    'id': '0057',
    'title': 'Min ti harh leh rawh',
    'language': 'mizo',
    'lyrics': mintiharhlehrawh,
    'link': 'https://youtu.be/j2rXDQxLyMY',
  },
  {
    'id': '0058',
    'title': 'Nang chauh i ni',
    'language': 'mizo',
    'lyrics': nangchauhini,
    'link': 'https://youtu.be/FSs3aOHhdBc',
  },
  {
    'id': '0059',
    'title': 'Nang fak zel che',
    'language': 'mizo',
    'lyrics': nangfakzelche,
    'link': 'https://youtu.be/zpiKFs9d7ys',
  },
  {
    'id': '0060',
    'title': 'Nang ka himna i ni si',
    'language': 'mizo',
    'lyrics': nangkahimnainisi,
    'link': 'https://youtu.be/F_draC2gnOM',
  },
  {
    'id': '0061',
    'title': 'Nang nen chuan',
    'language': 'mizo',
    'lyrics': nangnenchuan,
    'link': 'https://youtu.be/Ltlb3z5BEzs',
  },
  {
    'id': '0062',
    'title': 'Nazareth',
    'language': 'mizo',
    'lyrics': nazareth,
    'link': 'https://youtu.be/Bmv66qK4oK4',
  },
  {
    'id': '0063',
    'title': 'Nitin hian',
    'language': 'mizo',
    'lyrics': nitinhian,
    'link': 'https://youtu.be/OjdJblwxZ2c',
  },
  {
    'id': '0064',
    'title': 'Pathian hmel',
    'language': 'mizo',
    'lyrics': pathianhmelduhawm,
    'link': 'https://youtu.be/GxbMPtrhCVs',
  },
  {
    'id': '0065',
    'title': 'Pathian hnen ata ka bo hnu',
    'language': 'mizo',
    'lyrics': pathianhnenata,
    'link': 'https://youtu.be/vOWOtdaSn3I',
  },
  {
    'id': '0066',
    'title': 'Phuloh hmangaihna chu',
    'language': 'mizo',
    'lyrics': phulohmangaihna,
    'link': 'https://youtu.be/bBDROhI3A58',
  },
  {
    'id': '0067',
    'title': 'Rabboni',
    'language': 'mizo',
    'lyrics': rabboni,
    'link': 'https://youtu.be/oog8tybmCZE',
  },
  {
    'id': '0068',
    'title': 'Rimawi ropui ber',
    'language': 'mizo',
    'lyrics': rimawiropuiber,
    'link': 'https://youtu.be/MCPDAiku7TE',
  },
  {
    'id': '0069',
    'title': 'Rohlu Isua ka nei',
    'language': 'mizo',
    'lyrics': rohluisuakanei,
    'link': 'https://youtu.be/SWgkXwwf6jw',
  },
  {
    'id': '0070',
    'title': 'Siamtu duatlai',
    'language': 'mizo',
    'lyrics': siamduatlai,
    'link': 'https://youtu.be/jJ7gUTHXkiw',
  },
  {
    'id': '0071',
    'title': 'Thian tha ber Isua',
    'language': 'mizo',
    'lyrics': thianthaberisua,
    'link': 'https://youtu.be/bTti6eOWo_w',
  },
  {
    'id': '0072',
    'title': 'Thlei bik i nei lo',
    'language': 'mizo',
    'lyrics': thleibikaneilo,
    'link': 'https://youtu.be/FLRK7hWpmb4',
  },
  {
    'id': '0073',
    'title': 'Tlawm lua mah la',
    'language': 'mizo',
    'lyrics': tlawmluamahla,
    'link': 'https://youtu.be/tXnuAKvxWZs',
  },
  {
    'id': '0074',
    'title': 'Uire nu',
    'language': 'mizo',
    'lyrics': uirenu,
    'link': 'https://youtu.be/abFA9flHzZw',
  },
  {
    'id': '0075',
    'title': 'Van ruahtui',
    'language': 'mizo',
    'lyrics': vanruahtui,
    'link': 'https://youtu.be/pT7VT9xuyFE',
  },
  {
    'id': '1001',
    'title': 'A ku thatlôna chhôh lia (KHB 236)',
    'language': 'mara',
    'lyrics': akuthatlonachhohlia,
    'link': '',
  },
  {
    'id': '1002',
    'title': 'Ano ku ta einâ chhi tyh (KHB 386)',
    'language': 'mara',
    'lyrics': einachhityh,
    'link': '',
  },
  {
    'id': '1003',
    'title': 'Ato ei hlâ khai (KHB 391)',
    'language': 'mara',
    'lyrics': atoeihlakhai,
    'link': '',
  },
  {
    'id': '1004',
    'title': 'Beidyuchhai nah reithaina zydua',
    'language': 'mara',
    'lyrics': beidyuchhai,
    'link': 'https://youtu.be/uKiFmPAFavE',
  },
  {
    'id': '1005',
    'title': 'Beipa chaw pangai',
    'language': 'mara',
    'lyrics': beipachawpangai,
    'link': '',
  },
  {
    'id': '1006',
    'title': 'Beipa, ei vy hai (KHB 368)',
    'language': 'mara',
    'lyrics': beipaeivy,
    'link': '',
  },
  {
    'id': '1007',
    'title': 'Beipa na ngiathai mah y',
    'language': 'mara',
    'lyrics': beipanangiathaimahy,
    'link': 'https://youtu.be/ekHyMsYFrgs',
  },
  {
    'id': '1008',
    'title': 'Beipa, na pachâ chi (KHB 452)',
    'language': 'mara',
    'lyrics': beipanapachachi,
    'link': '',
  },
  {
    'id': '1009',
    'title': 'Beipa phana',
    'language': 'mara',
    'lyrics': beipaPhana,
    'link': 'https://youtu.be/hSSo6TwumFE',
  },
  {
    'id': '1010',
    'title': 'Cha kraw cha ei patu lyma aw (KHB 159)',
    'language': 'mara',
    'lyrics': chakrawchaeipatulymaaw,
    'link': '',
  },
  {
    'id': '1011',
    'title': 'Chhâzaw ta rônahna ta y se',
    'language': 'mara',
    'lyrics': chhazawtaronahnatayse,
    'link': '',
  },
  {
    'id': '1012',
    'title': 'Ei châ ly BEIPA',
    'language': 'mara',
    'lyrics': eichalybeipa,
    'link': 'https://youtu.be/swZNedFSn8I',
  },
  {
    'id': '1013',
    'title': 'Ei lôhngâhna chaipa na cha',
    'language': 'mara',
    'lyrics': eilongahnachaipa,
    'link': 'https://youtu.be/56H8adR25YU',
  },
  {
    'id': '1014',
    'title': 'Eina chhina maih ei sie aw (KHB 228)',
    'language': 'mara',
    'lyrics': einachhinamaiheisieaw,
    'link': '',
  },
  {
    'id': '1015',
    'title': 'Ei thyu aw na, ei paw o lȃ (KHB 379)',
    'language': 'mara',
    'lyrics': eithyuawnaeipawola,
    'link': '',
  },
  {
    'id': '1016',
    'title': 'Ei sah hlupi',
    'language': 'mara',
    'lyrics': eisahhlupi,
    'link': '',
  },
  {
    'id': '1017',
    'title': 'Ei va o lathloh',
    'language': 'mara',
    'lyrics': eivaolathlo,
    'link': 'https://youtu.be/TeT0iLCm4go',
  },
  {
    'id': '1018',
    'title': 'El Dorado (mara)',
    'language': 'mara',
    'lyrics': eldoradomara,
    'link': '',
  },
  {
    'id': '1019',
    'title': 'He khizaw râh lia bao hela',
    'language': 'mara',
    'lyrics': hekhizawrahliabaohela,
    'link': '',
  },
  {
    'id': '1020',
    'title': 'Hmotaotheina zy',
    'language': 'mara',
    'lyrics': hmotaotheinazy,
    'link': 'www.youtube.com/https://youtu.be/JIBdk8oz2Nk',
  },
  {
    'id': '1021',
    'title': 'Hosanna',
    'language': 'mara',
    'lyrics': hmotaotheinazy,
    'link': 'https://youtu.be/LBFuAC8BCSk',
  },
  {
    'id': '1022',
    'title': 'Hrona thikhao',
    'language': 'mara',
    'lyrics': hronatikhaokuabeileipa,
    'link': '',
  },
  {
    'id': '1023',
    'title': 'Hro krista',
    'language': 'mara',
    'lyrics': hrokrista,
    'link': 'https://youtu.be/FIf8KRTJZqE',
  },
  {
    'id': '1024',
    'title': 'Hy Beipa ei cha ngia ngaita',
    'language': 'mara',
    'lyrics': hybeipaeichangiangaita,
    'link': 'https://youtu.be/rsOOOxilPcM',
  },
  {
    'id': '1025',
    'title': 'Hy Bei Khazoh na hmotaopa zydua he',
    'language': 'mara',
    'lyrics': hybeikhazohnahmotaopazyduahe,
    'link': '',
  },
  {
    'id': '1026',
    'title': 'Hy Khazoh ! Nâ Beichhai na châ (KHB 25)',
    'language': 'mara',
    'lyrics': hykhazohna,
    'link': '',
  },
  {
    'id': '1027',
    'title': 'Hy rôhnah chai',
    'language': 'mara',
    'lyrics': hyrohnachai,
    'link': 'www.youtube.com/https://youtu.be/59vn_kwllD0',
  },
  {
    'id': '1028',
    'title': 'Hy, thisai rôhna chaipa (KHB 184)',
    'language': 'mara',
    'lyrics': krawliatathisaisohay,
    'link': '',
  },
  {
    'id': '1029',
    'title': 'Kei dei na siesai aw vei',
    'language': 'mara',
    'lyrics': keideinasiesaiawvei,
    'link': 'https://youtu.be/rZAwIdlUE8A',
  },
  {
    'id': '1030',
    'title': 'Kha reithai teh u',
    'language': 'mara',
    'lyrics': keideinasiesaiawvei,
    'link': 'https://youtu.be/Sdbb90xsb-Q',
  },
  {
    'id': '1031',
    'title': 'Khizaw hmozy hmâ pata',
    'language': 'mara',
    'lyrics': krawliatathisaisohay,
    'link': 'https://youtu.be/iIkV9LDw9jU',
  },
  {
    'id': '1032',
    'title': 'Khizaw thaina nah sona zy',
    'language': 'mara',
    'lyrics': khizawthainanahsohnazy,
    'link': 'https://youtu.be/W3ENO34TiOY',
  },
  {
    'id': '1033',
    'title': 'Khizaw he lei hrasa ',
    'language': 'mara',
    'lyrics': khizawheleihrasa,
    'link': 'https://youtu.be/agQaJATdueo',
  },
  {
    'id': '1034',
    'title': 'Khizaw chyhsa nata na mohmô lia',
    'language': 'mara',
    'lyrics': khizawchysanatanamohmolia,
    'link': 'https://youtu.be/KfTy7UXJd70',
  },
  {
    'id': '1035',
    'title': 'Khotalaina cha zisu ta na pie',
    'language': 'mara',
    'lyrics': khotalainachazisutanapie,
    'link': 'https://youtu.be/huZgQeB69No',
  },
  {
    'id': '1036',
    'title': 'Kraws thaby lia',
    'language': 'mara',
    'lyrics': krawsthabylia,
    'link': 'https://youtu.be/uzkztoVhLGU',
  },
  {
    'id': '1037',
    'title': 'Kraws va eima chaly',
    'language': 'mara',
    'lyrics': krawsvaeimachaly,
    'link': '',
  },
  {
    'id': '1038',
    'title': 'Krista â dai paki',
    'language': 'mara',
    'lyrics': kristaadaihpaki,
    'link': 'https://youtu.be/2remIRVtBy8',
  },
  {
    'id': '1039',
    'title': 'Kyhpachana hla ta ei sa aw',
    'language': 'mara',
    'lyrics': kristaadaihpaki,
    'link': 'https://youtu.be/IEYNyQoLwdI',
  },
  {
    'id': '1040',
    'title': 'Kyhpachâna! Noâh â chhih (KHB 136)',
    'language': 'mara',
    'lyrics': kyhpachanareitheisala,
    'link': '',
  },
  {
    'id': '1041',
    'title': 'Moh la na hro aw(KHB 241)',
    'language': 'mara',
    'lyrics': mohlanahroaw,
    'link': 'https://youtu.be/AbcSHAOO47k',
  },
  {
    'id': '1042',
    'title': 'Moh ngia chhaipa',
    'language': 'mara',
    'lyrics': mohngichaipaacha,
    'link': '',
  },
  {
    'id': '1043',
    'title': 'Na molei phaohri pahlei na khoh ma?',
    'language': 'mara',
    'lyrics': namoleiphaohripahleinakhoma,
    'link': '',
  },
  {
    'id': '1044',
    'title': 'Nazari zisu',
    'language': 'mara',
    'lyrics': nazarizisu,
    'link': 'https://youtu.be/6iHIJJRmDmQ',
  },
  {
    'id': '1045',
    'title': 'Olive thohna',
    'language': 'mara',
    'lyrics': olivethohna,
    'link': 'https://youtu.be/bloAnrWE_ZY',
  },
  {
    'id': '1046',
    'title': 'Pachhatuh a hro',
    'language': 'mara',
    'lyrics': pachhatuhahro,
    'link': '',
  },
  {
    'id': '1047',
    'title': 'Pachhatuh, kei na khôsai kha(KHB 226)',
    'language': 'mara',
    'lyrics': pachhatuhkeinakhosaikha,
    'link': 'https://youtu.be/MXbYaqMSCUY',
  },
  {
    'id': '1048',
    'title': 'Pakho teh u (KHB 129)',
    'language': 'mara',
    'lyrics': pakhotehu,
    'link': '',
  },
  {
    'id': '1049',
    'title': 'Pathipalôh molei chiehpa (KHB 370)',
    'language': 'mara',
    'lyrics': pathipalomoleichhipa,
    'link': 'https://youtu.be/qGktLgQc5zM',
  },
  {
    'id': '1050',
    'title': 'Paw Khazoh kypachâna',
    'language': 'mara',
    'lyrics': pawkypachana,
    'link': 'https://youtu.be/7K1uymXt_jM/https://youtu.be/FPVK5EAwhSQ',
  },
  {
    'id': '1051',
    'title': 'Râh taipa lâ',
    'language': 'mara',
    'lyrics': rahtaipala,
    'link': 'https://youtu.be/d77NSEVAwBM',
  },
  {
    'id': '1052',
    'title': 'Reithaina',
    'language': 'mara',
    'lyrics': reithaina,
    'link': '',
  },
  {
    'id': '1053',
    'title': 'Reithai teh u khizaw zydua sai u',
    'language': 'mara',
    'lyrics': shouttothelord,
    'link': '',
  },
  {
    'id': '1054',
    'title': 'Sakhih dâhphipa hawh',
    'language': 'mara',
    'lyrics': sakhihdahphipahawhbeipa,
    'link': 'https://youtu.be/fvMvjed18Hg',
  },
  {
    'id': '1055',
    'title': 'Sie para suh',
    'language': 'mara',
    'lyrics': sieparasuh,
    'link': 'https://youtu.be/wvVs-vCxZlg',
  },
  {
    'id': '1056',
    'title': 'Still',
    'language': 'mara',
    'lyrics': still,
    'link': 'https://youtu.be/cEPuUqpLnV4',
  },
  {
    'id': '1057',
    'title': 'Thlahpa Pathaih',
    'language': 'mara',
    'lyrics': thlapapathai,
    'link': 'https://youtu.be/cEPuUqpLnV4',
  },
  {
    'id': '1058',
    'title': 'The blessing',
    'language': 'mara',
    'lyrics': theblessing,
    'link': 'https://youtu.be/-PsiNNB8UkA',
  },
  {
    'id': '1059',
    'title': 'Ti, wine lâ na pachâsa',
    'language': 'mara',
    'lyrics': tiwinelapachasa,
    'link': '',
  },
  {
    'id': '1060',
    'title': 'Zisu ei hnabeiseina',
    'language': 'mara',
    'lyrics': eimalikalialeichiepaay,
    'link': '',
  },
  {
    'id': '1061',
    'title': 'Zisu ei viasa pha chai',
    'language': 'mara',
    'lyrics': zisueiviasaphachhai,
    'link': 'https://youtu.be/k6cuQwd9yhE',
  },
  {
    'id': '1062',
    'title': 'Zisu eima viasa pha chai (KHB 151)',
    'language': 'mara',
    'lyrics': zisueimaviasaphachhai,
    'link': 'https://youtu.be/k6cuQwd9yhE',
  },
  {
    'id': '1063',
    'title': 'Zisu hnei ei khoh via (KHB 229)',
    'language': 'mara',
    'lyrics': zisuhneieikhohvia,
    'link': 'https://youtu.be/k6cuQwd9yhE',
  },
  {
    'id': '2001',
    'title': 'Ape',
    'language': 'dance',
    'lyrics': ape,
    'link': 'https://youtu.be/bIcOwRCfoWU',
  },
  {
    'id': '2002',
    'title': 'Chacha la ei pasie',
    'language': 'dance',
    'lyrics': chachalaeipasie,
    'link': 'https://youtu.be/hVt5sKduKLA',
  },
  {
    'id': '2003',
    'title': 'Ei reithai lyma aw',
    'language': 'dance',
    'lyrics': eireithailymaaw,
    'link': '',
  },
  {
    'id': '2004',
    'title': 'Hallelujah',
    'language': 'dance',
    'lyrics': hallelujah,
    'link': '',
  },
  {
    'id': '2005',
    'title': 'Hlimna kim',
    'language': 'dance',
    'lyrics': hlimnakim,
    'link': 'https://youtu.be/HiCFTRiBMnc',
  },
  {
    'id': '2006',
    'title': 'Na hro lia lyna na kho ma',
    'language': 'dance',
    'lyrics': nahrolialynanakhoma,
    'link': '',
  },
  {
    'id': '2007',
    'title': 'Na lia ato ei tao thei',
    'language': 'dance',
    'lyrics': naliaatoeitaothei,
    'link': '',
  },
  {
    'id': '2008',
    'title': 'Tui nung lui chu',
    'language': 'dance',
    'lyrics': tuinungluichu,
    'link': 'https://youtu.be/t1OCbUIkg5U',
  },
];
