const maraSongTitles = [
  '1.  A ku thatlôna chhôh lia (KHB 236)',
  '2.  Ano ku ta einâ chhi tyh (KHB 386)',
  '3.  Ato ei hlâ khai (KHB 391) ',
  '4.  Beipa chaw pangai',
  '5.  Beipa, ei vy hai (KHB 368)',
  '6.  Beipa na ngiathai mah y',
  '7.  Beipa, na pachâ chi (KHB 452)',
  '8.  Beipa phana ',
  '9.  Cha kraw cha ei patu lyma aw (KHB 159)',
  '10. Chhâzaw ta rônahna ta y se',
  '11. Eina chhina maih ei sie aw (KHB 228)',
  '12. Ei thyu aw na, ei paw o lȃ (KHB 379)',
  '13. Ei sah hlupi',
  '14. El Dorado',
  '15. He khizaw râh lia bao hela',
  '16. Hmotaotheina zy',
  '17. Hrona thikhao',
  '18. Hy Beipa ei cha ngia ngaita',
  '19. Hy Bei Khazoh na hmotaopa zydua he',
  '20. Hy Khazoh ! Nâ Beichhai na châ (KHB 25)',
  '21. Hy rôhnah chai',
  '22. Hy, thisai rôhna chaipa (KHB 184)',
  '23. Kei dei na siesai aw vei',
  '24. Khizaw hmozy hmâ pata',
  '25. Khizaw thaina nah sona zy',
  '26. Khizaw he lei hrasa ',
  '27. Khizaw chyhsa nata na mohmô lia',
  '28. Khotalaina cha zisu ta na pie',
  '29. Kraws thaby lia',
  '30. Kraws va eima chaly ',
  '31. Krista â dai paki',
  '32. Kyhpachâna! Noâh â chhih (KHB 136)',
  '33. Moh la na hro aw(KHB 241)',
  '34. Moh ngia chhaipa ',
  '35. Na molei phaohri pahlei na khoh ma?',
  '36. Nazari zisu'
      '37. Olive thohna',
  '38. Pachhatuh a hro',
  '39. Pachhatuh, kei na khôsai kha(KHB 226)',
  '40. Pakho teh u (KHB 129)',
  '41. Pathipalôh molei chiehpa (KHB 370) ',
  '42. Paw Khazoh kypachâna',
  '43. Reithai teh u khizaw zydua sai u',
  '44. Sakhih dâhphipa hawh',
  '45. Still',
  '46. Thlahpa Pathaih ',
  '47. The blessing',
  '48. Ti, wine lâ na pachâsa',
  '49. Zisu ei hnabeiseina',
  '50. Zisu ei viasa pha chai',
  '51. Zisu eima viasa pha chai (KHB 151)',
  '52. Zisu hnei ei khoh via (KHB 229)',
];

const mizoSongTitles = [
  '1.  A hmangaihna a lo ni',
  '2.  An hrilhfiah',
  '3.  Aman engkimah min hria e',
  '4.  Amen ka pe lo thei lo',
  '5.  Amen! Silfai ka ni',
  '6.  A ṭha e',
  '7.  Aw ropuiber',
  '8.  Bultan min phal sak',
  '9.  Chawimawina',
  '10. Chhandamtu min hruaina lamtluang',
  '11. Danglamlo krista',
  '12. Duhthlanna sang ber',
  '13. Engtia awm thei nge?',
  '14. Eng vang nge',
  '15. El Dorado',
  '16. Hmangaihtu',
  '17. Hringnun kan zin kawngah hian',
  '18. Hriatchian lehzual che hi',
  '19. I hlu a ni',
  '20. I lam kan lo hawi',
  '21. Indona',
  '22. Isua Lal ber ani',
  '23. I zalen',
  '24. Ka dam lai nun kawng',
  '25. Ka dai zel dawn',
  '26. Ka duh ber Lalpa',
  '27. ka hnaih nan che',
  '28. Ka lawm e Isu',
  '29. Ka lawm e Lalpa',
  '30. ka lo kir e',
  '31. Kan fak che',
  '32. Kan thinlung kan hlan che',
  '33. Ka nun hnâr kaitu',
  '34. Kan zai I tan',
  '35. Ka rawn in hlan e',
  '36. Ka rinchhan Lalpa',
  '37. Ka ring zel ang che',
  '38. Ka tawrh hi Lalpan a phal',
  '39. Ka tling si lo',
  '40. Ka thinglungah a nung',
  '41. Ka thupui ber',
  '42. Ka zawng zawng hian fak che a nuam',
  '43. Khawngaihna',
  '44. Kraws kawng',
  '45. Lalpa atha ani',
  '46. Lalpa atha',
  '47. Lalpa thatna',
  '48. Lalpa Ini',
  '49. Lalpa mi hriat ',
  '50. Lalpan min hria ',
  '51. Lalpa remruat ',
  '52. Min chhung khat la',
  '53. Min dilsak thin',
  '54. Min hmangaih loh i thei lo',
  '55. Min hmangaih si a',
  '56. Min hruai la ka zui ang che',
  '57. Min ti harh leh rawh',
  '58. Nang chauh i ni',
  '59. Nang fak zel che',
  '60. Nang ka himna i ni si',
  '61. Nang nen chuan',
  '62. Nazareth',
  '63. Nitin hian',
  '64. Pathian hmel',
  '65. Pathian hnen ata ka bo hnu',
  '66. Phuloh hmangaihna chu',
  '67. Rabboni',
  '68. Rimawi ropui ber',
  '69. Rohlu Isua ka nei',
  '70. Siamtu duatlai',
  '71. Thian tha ber Isua',
  '72. Thlei bik i nei lo',
  '73. Tlawm lua mah la',
  '74. Uire nu',
  '75. Van ruahtui',
];

const danceSongTitles = [
  '1. Ape',
  '2. Chacha la ei pasie',
  '3. Ei reithai lyma aw',
  '4. Hallelujah',
  '5. Hlimna kim ',
  '6. Na hro lia lyna na kho ma',
  '7. Na lia ato ei tao thei',
  '8. Tui nung lui chu',
];
